version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: uniper_mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=uniper_mongodb
    volumes:
      - ./data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  volume:
    mongodb_data:
      name: uniper_mongodb_data